services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    networks:
      - networks-visualizer-tool
     
  client:
    build:
      context: ./client
    volumes:
      - staticbuild:/app/out
    networks:
      - networks-visualizer-tool

  networks:
    networks-visualizer-tool:
      driver: bridge
      
  volumes:
    staticbuild: